server:
  profiles:
    active: dev
  servlet:
    context-path: /graph
  tomcat:
    accesslog:
      enabled: true
      directory: ${logging.path}

spring:
  application:
    name: graph-bed-web

#logging:
#  config: classpath:log4j.xml.temp
#  path: /data/log/goocity/