spring:
  application:
    name: graph-bed-provider
  datasource:
    username: root
    password: TengXunYun@2018
    url: jdbc:mysql://mysql.whforever.cn:3306/graph-bed?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8

mybatis:
  mapperLocations: classpath:mappings/*.xml

dubbo:
  registry:
    address: N/A
  protocol:
    port: 12345
    name: dubbo
  scan:
    base-packages: com.whfstudio.graphbed
